services:
  rabbit:
    image: rabbitmq:3-management
    container_name: sagi.sdk.rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=passw0rd 